#!/usr/bin/perl
#############################################################
#
# Usage:  build_html_book <file of categories> <Release>
#
#
#############################################################
#
require (build_html_section);

if ($#ARGV != 1) {
    print "Usage:  build_html_book <file of categories> <release>\n";
    exit;
}

if (open(CATEGORIES,"<$ARGV[0]") == 0) { 
    print "$ARGV[0] could not be opened.\n";
    exit;
} else { # do the entries listed in a file
    @categories = ();
    while (<CATEGORIES>) {
	chop;
	mkdir($_);
	push(@categories,$_);
    }
}

if (open(BOOK_SUM,">${ARGV[1]}_STPS_toc.html") == 0) {
    print "Output file for book summary can not be opened: ${ARGV[1]}STPS_toc.html\n";
    exit;
}
print (BOOK_SUM "<html>\n");
print (BOOK_SUM "<style>\n");
print (BOOK_SUM "body { background-color: white; }\n");
print (BOOK_SUM "body { font-family: sans-serif; }\n");
print (BOOK_SUM "li { font-size: 80%; }\n");
print (BOOK_SUM "</style>\n");
print (BOOK_SUM "<center>\n");
print (BOOK_SUM "<h1>${ARGV[1]} STPS Table of Contents</h1>\n");
print (BOOK_SUM "</center>\n");
print (BOOK_SUM "<body>\n");
print (BOOK_SUM "<ol>\n");

while ($category=shift(@categories)) {

    ($status, $overall_test_status) = build_html_section($category,$category);
    if (($status ne 'successful') && ($category ne '')) {
        print "Test category $category is not consistent and will be marked so.  This usually indicates that the test was running during the book build process\n";
        #system($cmd);
    }
    if (($overall_test_status eq 'pass') && ($status eq 'successful')) {
        print (BOOK_SUM "<li> <a style=\"color: #00F000\" href=${category}_toc.html>$category</a></ul></li>\n");
    } elsif (($overall_test_status eq 'fail') && ($status eq 'successful')) {
        print (BOOK_SUM "<li> <a style=\"color: #FF0000\" href=${category}_toc.html>$category</a></ul></li>\n");
    } else {
        if ($status eq 'successful') {
            print (BOOK_SUM "<li> <a href=${category}_toc.html>$category</a></ul></li>\n");
	} else {
            print (BOOK_SUM "<li> <a style=\"color: #00FFFF\" href=${category}_toc.html>$category</a></ul></li>\n");
	}
    }

}
print (BOOK_SUM "<li> <a href=req_test_id.html>Requirements to Test Case ID Trace</a></ul></li>\n");  
print (BOOK_SUM "<li> <a href=test_id_req.html>Test Case ID to Requirements Trace</a></ul></li>\n");  
print (BOOK_SUM "<li> <a href=log_entry.html>Log Entry Utility</a></ul></li>\n");  
print (BOOK_SUM "</ol>\n");
print (BOOK_SUM "</body>\n");
print (BOOK_SUM "</html>\n");
close (BOOK_SUM);
